//! Export a loop configuration to a standalone bash script.

//! The generated script replicates the loopgen LOOP_STATUS protocol
//! using only `claude -p`, `grep`, and standard shell utilities.

use crate::config_file::FileConfig;

fn sh(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\\\''"))
}

/// Render a `FileConfig` as a self-contained bash script.
pub fn render(cfg: &FileConfig) -> String {
    let mut s = String::new();

    // Shebang + header
    s.push_str("#!/usr/bin/env bash\n");
    s.push_str("# Generated by loopgen — agentic loop runner for Claude Code.\n");
    s.push_str("# Run: bash <this-file>  or  ./<this-file>\n");
    s.push_str("set -uo pipefail\n\n");

    // Config variables
    s.push_str(&format!("MAX={}\n", cfg.max));
    s.push_str(&format!("GOAL={}\n", sh(&cfg.goal)));
    if let Some(v) = &cfg.verify {
        s.push_str(&format!("VERIFY={}\n", sh(v)));
    }
    if let Some(d) = &cfg.dod {
        s.push_str(&format!("DOD={}\n", sh(d)));
    }
    if let Some(m) = &cfg.model {
        s.push_str(&format!("MODEL_OPT=--model {}\n", sh(m)));
    } else {
        s.push_str("MODEL_OPT=\n");
    }
    s.push('\n');

    // Build the harness prompt
    s.push_str("HARNESS=$(cat <<'HARNESS_EOF'\n");
    s.push_str("# AGENTIC LOOP\n\n");
    s.push_str("## Goal\n");
    s.push_str(&cfg.goal);
    s.push_str("\n\n");

    // Definition of Done
    s.push_str("## Definition of Done\n");
    match (&cfg.verify, &cfg.dod) {
        (Some(cmd), _) => {
            s.push_str(&format!(
                "The stated goal is achieved and the verify command (`{}`) exits 0.\n",
                cmd
            ));
        }
        (None, Some(dod_text)) => {
            s.push_str(dod_text);
            s.push('\n');
        }
        (None, None) => {
            s.push_str("The stated goal is fully achieved, with concrete evidence cited for each success criterion.\n");
        }
    }
    s.push_str("\n");

    // Cycle instructions
    s.push_str("## Cycle (repeat each iteration)\n");
    s.push_str("1. PLAN   — state the smallest next increment toward the goal.\n");
    s.push_str("2. ACT    — do it. For non-trivial work spawn a worker; otherwise act directly.\n");
    s.push_str("3. VERIFY — check progress against the Definition of Done.\n");
    s.push_str("4. REPORT — emit exactly one line, this format:\n");
    s.push_str("          LOOP_STATUS: <DONE|CONTINUE|BLOCKED> | iter <n>/${MAX} | <one-line note>\n");
    s.push_str("5. CARRY  — update a running STATE summary.\n");
    s.push_str("\n");
    s.push_str("## Termination\n");
    s.push_str("- Continue while status == CONTINUE and iter < ${MAX}.\n");
    s.push_str("- Stop on DONE, BLOCKED, or iter == ${MAX}.\n");
    s.push_str("\n");
    s.push_str("## Begin\n");
    s.push_str("Start at iteration 1.\n");
    s.push_str("HARNESS_EOF\n)\n\n");

    // State tracking
    s.push_str("STATE=\"(none — first iteration).\"\n\n");

    // Main loop
    s.push_str("for ((i=1; i<=MAX; i++)); do\n");
    s.push_str("  echo \"\u2500\u2500 iteration $i / $MAX \u2500\u2500\"\n\n");

    // Compose prompt
    s.push_str("  PROMPT=\"${HARNESS}\n\n## Running state (prior iterations)\n${STATE}\n\n## This is iteration ${i} of ${MAX}. Do ONE increment, then emit the LOOP_STATUS line.\"\n\n");

    // Invoke claude
    s.push_str("  RESPONSE=$(claude -p \"${PROMPT}\" --output-format json ${MODEL_OPT} 2>/dev/null)\n\n");

    // Extract result text
    s.push_str("  # Try to extract .result from JSON; fall back to raw output\n");
    s.push_str("  RESULT=$(echo \"${RESPONSE}\" | python3 -c \"import sys,json\n");
    s.push_str("try:\n");
    s.push_str("    d=json.load(sys.stdin)\n");
    s.push_str("    print(d.get('result',''))\n");
    s.push_str("except: pass\n" 2>/dev/null)\n");
    s.push_str("  : \"${RESULT:=${RESPONSE}}\"\n\n");

    // Parse LOOP_STATUS
    s.push_str("  # Extract LOOP_STATUS (case-insensitive, last match wins)\n");
    s.push_str("  STATUS=$(echo \"${RESULT}\" | grep -ioP 'LOOP_STATUS:\\s*(DONE|CONTINUE|BLOCKED)' | tail -1 | grep -ioP '(DONE|CONTINUE|BLOCKED)')\n");
    s.push_str("  : \"${STATUS:=CONTINUE}\"\n\n");

    // Handle DONE with optional verify
    s.push_str("  case \"${STATUS}\" in\n");
    s.push_str("    DONE)\n");
    if let Some(v) = &cfg.verify {
        s.push_str("      echo \"  verifying: ${VERIFY}\"\n");
        s.push_str(&format!("      if eval {} 2>&1; then\n", sh(v)));
        s.push_str("        echo \"\u2713 DONE (verified) on iteration $i\"\n");
        s.push_str("        exit 0\n");
        s.push_str("      else\n");
        s.push_str("        echo \"  DONE claimed but verify failed \u2014 continuing as CONTINUE\"\n");
        s.push_str("        STATUS=CONTINUE\n");
        s.push_str("      fi\n");
        s.push_str("      ;;\n");
    } else {
        s.push_str("      echo \"\u2713 DONE on iteration $i\"\n");
        s.push_str("      exit 0\n");
        s.push_str("      ;;\n");
    }
    s.push_str("    BLOCKED)\n");
    s.push_str("      echo \"\u25a0 BLOCKED on iteration $i\"\n");
    s.push_str("      exit 2\n");
    s.push_str("      ;;\n");
    s.push_str("    CONTINUE|*)\n");
    s.push_str("      echo \"  [iter $i/$MAX] CONTINUE\"\n");
    s.push_str("      ;;\n");
    s.push_str("  esac\n\n");

    // Update state
    s.push_str("  # Append truncated summary to state\n");
    s.push_str("  SUMMARY=$(echo \"${RESULT}\" | tail -c 200)\n");
    s.push_str("  STATE=\"${STATE}\n\n[iteration ${i}] ${SUMMARY}\"\n");
    s.push_str("  # Cap state at 4000 chars (keep tail)\n");
    s.push_str("  if [ ${#STATE} -gt 4000 ]; then\n");
    s.push_str("    STATE=\"\u2026(truncated)\u2026${STATE: -4000}\"\n");
    s.push_str("  fi\n\n");
    s.push_str("done\n\n");

    // Exhausted iterations
    s.push_str("echo \"\u2717 reached --max ($MAX) without DONE\"\n");
    s.push_str("exit 3\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal_cfg() -> FileConfig {
        FileConfig {
            goal: "test goal".to_string(),
            max: 4,
            verify: None,
            dod: None,
            model: None,
            max_state_chars: 4000,
            claude_bin: "claude".to_string(),
            verbose: false,
        }
    }

    #[test]
    fn starts_with_shebang() {
        let out = render(&minimal_cfg());
        assert!(out.starts_with("#!/usr/bin/env bash"));
    }

    #[test]
    fn contains_goal() {
        let cfg = FileConfig {
            goal: "fix the parser bug".to_string(),
            ..minimal_cfg()
        };
        let out = render(&cfg);
        assert!(out.contains("fix the parser bug"));
    }

    #[test]
    fn contains_max() {
        let out = render(&minimal_cfg());
        assert!(out.contains("MAX=4"));
    }

    #[test]
    fn contains_loop_status_protocol() {
        let out = render(&minimal_cfg());
        assert!(out.contains("LOOP_STATUS"));
        assert!(out.contains("DONE|CONTINUE|BLOCKED"));
    }

    #[test]
    fn contains_verify_when_set() {
        let cfg = FileConfig {
            verify: Some("cargo test".to_string()),
            ..minimal_cfg()
        };
        let out = render(&cfg);
        assert!(out.contains("VERIFY="));
        assert!(out.contains("verifying:"));
        assert!(out.contains("DONE claimed but verify failed"));
    }

    #[test]
    fn no_verify_when_unset() {
        let out = render(&minimal_cfg());
        assert!(!out.contains("VERIFY="));
        assert!(!out.contains("verifying:"));
    }

    #[test]
    fn contains_exit_codes() {
        let out = render(&minimal_cfg());
        assert!(out.contains("exit 0"));   // DONE
        assert!(out.contains("exit 2"));   // BLOCKED
        assert!(out.contains("exit 3"));   // MaxReached
    }

    #[test]
    fn contains_model_when_set() {
        let cfg = FileConfig {
            model: Some("opus".to_string()),
            ..minimal_cfg()
        };
        let out = render(&cfg);
        assert!(out.contains("--model"));
        assert!(out.contains("opus"));
    }

    #[test]
    fn contains_harness_structure() {
        let out = render(&minimal_cfg());
        assert!(out.contains("# AGENTIC LOOP"));
        assert!(out.contains("## Goal"));
        assert!(out.contains("## Definition of Done"));
        assert!(out.contains("## Cycle"));
        assert!(out.contains("## Begin"));
    }

    #[test]
    fn special_chars_in_goal_are_quoted() {
        let cfg = FileConfig {
            goal: "it's a \"test\"".to_string(),
            ..minimal_cfg()
        };
        let out = render(&cfg);
        // Should not break the bash script
        assert!(out.contains("'it'\\''s a \"test\"'"));
    }

    #[test]
    fn contains_state_management() {
        let out = render(&minimal_cfg());
        assert!(out.contains("STATE="));
        assert!(out.contains("truncated"));
    }
}
